kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.kamil: apiKey, login
  admin.enabled: "false"
