apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml
patches:
  - path: prod/argocd-server.yaml
    target:
      kind: Service
      name: argocd-server
  - path: prod/argocd-cm-users.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: prod/argocd-rbac-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
