apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    name: argocd
spec:
  project: default
  destination:
    namespace: argocd 
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/retail-store-saas/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/argocd
